### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by ghost** [manateeworks/phonegap-manateeworks-v3#1]
![ios-plist](https://cloud.githubusercontent.com/assets/5564013/23270653/da3fda0c-f9f4-11e6-9944-fd3bb246ce59.png)
![android-manifest](https://cloud.githubusercontent.com/assets/5564013/23270678/e9836010-f9f4-11e6-9e4e-c780b7af6d94.png)

**Comment by ghost** [comment]
![windows_resw](https://cloud.githubusercontent.com/assets/5564013/23270749/33a2168c-f9f5-11e6-947a-25041ecf5376.png)

**Comment by ghost** [comment]
Windows UWP needs webcam permission, should be added automatically with the addition of the plugin, but if it fails, it needs to be enabled...
![image](https://cloud.githubusercontent.com/assets/5564013/23271042/515bc528-f9f6-11e6-8210-cbd97fd42a04.png)

**Comment by ghost** [comment]
Examples uploaded separately to avoid conflicts on some platforms
[examples.zip](https://github.com/manateeworks/phonegap-manateeworks-v3/files/797274/examples.zip)

**Comment by lazyvlad** [comment]
![da3fda0c-f9f4-11e6-9944-fd3bb246ce59](https://cloud.githubusercontent.com/assets/226620/24711310/dad61c7e-1a1f-11e7-948b-802898348c2c.png)
