### ISSUE TITLE
Overlay visible after scanned item

### ISSUE THREAD

**Issue by cherimo** [manateeworks/phonegap-manateeworks-v3#11]
Hey,

I am using the overlay mode for the scanning and below the overlay you can see the scanned items.
After scanning a product the overlay closes, but what I really want for some time now is that the overlay stays after an item is scanned.

Is this possible?

Greets,
Cherimo

**Comment by ghost** [comment]
Hi
1. Can you please tell us what platform you are using ( Android, iOS or Windows )
2. Can you please share your code/project so we can make some tests

Regards,

**Comment by cherimo** [comment]
Thank you for your response, I am using Cordova for Android.

Here is an simple example of the code:

`<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="msapplication-tap-highlight" content="no" />
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" />
    <link rel="stylesheet" type="text/css" href="css/index.css" />
</head>

<body>

    <div class="app">

        <ul id="scanlist"></ul>
        <ul id="mwb_list"></ul>

    </div>
    <script type="text/javascript" src="cordova.js"></script>
    <script type="text/javascript" src="js/index.js"></script>
    <script type="text/javascript" src="js/MWBConfig.js"></script>
    <script type="text/javascript">
        app.initialize();

        //open 50% vertical scanwindow
        mwbScanner.startScanning(function (result)
        {
            appendScan(result);
        }
        , 0, 4, 100, 50);

        function appendScan(result) {
            var div = document.createElement('div');
            div.className = 'row';
            div.innerHTML = "<div class='line'>" + result.code + " / " + result.type + "</div>";
            document.getElementById('scanlist').appendChild(div);
        }

    </script>
</body>

</html>
`

Is it possible to display the scan window even after the item is scanned?
Now it closes on every scan.

Thanks in advance.

**Comment by ghost** [comment]
Hi @cherimo ,

To keep the preview/overlay running after a scan, use this setting:
`{"method" : "MWBcloseScannerOnDecode", "value" : [false]}`

(default is true) along with the rest of the settings in MWBConfig.js. After this, the preview will stay but the scanning will be paused. You can either close it yourself, or call 
`mwbScanner.resumeScanning()`

to perform continuous scanning.

Best regards,
Team Manatee
