### ISSUE TITLE
what is the best way to parse driver's license information from pdf417

### ISSUE THREAD

**Issue by bhupathibhargva** [manateeworks/phonegap-manateeworks-v3#16]
i woud like to get dl information from scanning the barcode at the back of drivers license .
but when i print  response. i get see a string starting @ansi324535636......   are there any specific guideline to parse this information to first name last name  dob etc?. i scanned licenses of two different states and it looks like this string follows different convention please help me out.

**Comment by ghost** [comment]
Hi @bhupathibhargva ,

You can use the method `MWBsetActiveParser` with `MWP_PARSER_MASK_AAMVA` as argument. The easiest way to do this is by modifying the `js\MWBConfig.js` file by adding the following line in the array of settings:

```javascript
{'method' : 'MWBsetActiveParser', 'value' : [mw_c.MWP_PARSER_MASK_AAMVA]}
```

Don't forget to separate from other settings with a comma, otherwise your settings won't load.

Of course you should also include that script in the `index.html` file:
```html
<script type="text/javascript" src="js/MWBConfig.js"></script>
```
and call `scannerConfig();` inside the `onDeviceReady` function in `js\index.js`.

This should return an AAMVA parsed result in JSON format. Note that AAMVA has issued many versions of the standard, the current one being from 2016, but some states still have DLs with older AAMVA standard version, even as far back as from the year 2000. Some fields were encoded differently in older versions (for example the date format is different), so the result fields for those DLs are different that the ones encoded with the latest standard.

Best regards,
Team Manatee

**Comment by bhupathibhargva** [comment]
Hi ,
I am using ionic 2 is it the same procedure for ionic 2 also? I tried adding scannerConfig();inside ondevice ready but ...im getting an error saying cannot find name scannerConfig...should i import something ?  
I also tried using the entire mwbScanner inside one of my methods where i was able print the response with cusstom settings but my scanned data is still ansi33444..... Also,if possible can you please share with me sample implementation of customsettings or AAMVA PARSING  for ionic 2 i would be of great help.
Also, is the expect output from AAMVA parsed data   @ansi233322....... or does it return an object ?
Thanks in advance.
Bhupathibhargav@gmail.com

**Comment by lazyvlad** [comment]
Hi @bhupathibhargva 
Can you please take a look at how we've used our plugin in an ionic2 solution.
You can check here:
https://github.com/manateeworks/manateeworks-barcodescanner-ionic-starter/blob/master/src/app/app.component.ts
in the 
```
      manateeScanner.config(()=>{

          manateeScanner.scanner.setCallback((result:any) =>{});
          var mw_c:any =  manateeScanner.scanner.getConstants();
          var settings : any = [
                  {"method" : 'MWBenableZoom', "value" : [true]}
                  ,{"method" : 'MWBsetZoomLevels', "value" : [200, 400, 1]}
                  ,{"method" : 'MWBsetInterfaceOrientation', "value" : [mw_c.OrientationLandscapeLeft]}
                  // {"method" : 'MWBsetOverlayMode', "value" : [mw_c.OverlayModeImage]}
              ];
          var keys : any = {
              'Android'   : "VALID_ANDROID_KEY",
              'iOS'       : "VALID IOS KEY",
              'Win32NT'   : "VALID_WIN_WP8_KEY",
              'windows'   : "VALID_WIN_10_UWP_KEY"
          };
          var key : any = (keys[device.platform])?keys[device.platform]:'';

          return manateeScanner.scanner.setKey(key).then((response:any)=>{
              return manateeScanner.scanner.loadSettings(settings).then((response:any)=>{}).catch((reason:any)=>{
                              console.log(reason);
                          });
          });
        }); 
```
you can see how we use the settings. So for your needs you just need to add the

`{'method' : 'MWBsetActiveParser', 'value' : [mw_c.MWP_PARSER_MASK_AAMVA]}`

in the settings array. 
Keep in mind that your license key needs to be generated with the PARSERS unlocked in order for it to work.


Regards

**Comment by ghost** [comment]
Hi @bhupathibhargva 
Can you please take a look at how we've used our plugin in an ionic2 solution.
You can check here:
https://github.com/manateeworks/manateeworks-barcodescanner-ionic-starter/blob/master/src/app/app.component.ts
in the 
```
      manateeScanner.config(()=>{

          manateeScanner.scanner.setCallback((result:any) =>{});
          var mw_c:any =  manateeScanner.scanner.getConstants();
          var settings : any = [
                  {"method" : 'MWBenableZoom', "value" : [true]}
                  ,{"method" : 'MWBsetZoomLevels', "value" : [200, 400, 1]}
                  ,{"method" : 'MWBsetInterfaceOrientation', "value" : [mw_c.OrientationLandscapeLeft]}
                  // {"method" : 'MWBsetOverlayMode', "value" : [mw_c.OverlayModeImage]}
              ];
          var keys : any = {
              'Android'   : "VALID_ANDROID_KEY",
              'iOS'       : "VALID IOS KEY",
              'Win32NT'   : "VALID_WIN_WP8_KEY",
              'windows'   : "VALID_WIN_10_UWP_KEY"
          };
          var key : any = (keys[device.platform])?keys[device.platform]:'';

          return manateeScanner.scanner.setKey(key).then((response:any)=>{
              return manateeScanner.scanner.loadSettings(settings).then((response:any)=>{}).catch((reason:any)=>{
                              console.log(reason);
                          });
          });
        }); 
```
you can see how we use the settings. So for your needs you just need to add the

`{'method' : 'MWBsetActiveParser', 'value' : [mw_c.MWP_PARSER_MASK_AAMVA]}`

in the settings array. 
Keep in mind that your license key needs to be generated with the PARSERS unlocked in order for it to work.


Regards
Team Manatee
