### ISSUE TITLE
Barcode scanner stops reading QR or barcodes after reading 81 times in iOS

### ISSUE THREAD

**Issue by arruix** [manateeworks/phonegap-manateeworks-v3#2]
I have an issue with the plugin, after reading more that 80 barcodes in iOS 9.2 or 10.x, is opening the barcode reader screen but not read anything, I'm using your example code that you provide at the bottom.

Cordova version 6.4.0
Plugin version 3.0.14

**Comment by ghost** [comment]
arruix sorry for your inconvenience, we will investigate this issue.

Can you tell me is this happening when using the full screen scanner, or while using the windowed (cropped) view?

**Comment by arruix** [comment]
This error is happening in all the views( full screen, widowed view 50-100), the only way to continue reading is kill the app and re-launch again.

**Comment by ghost** [comment]
Thanks, we are aware of the issue now, working on fixing it.

**Comment by ghost** [comment]
Arruix can you give a look at the new version 3.0.15 and see if the issue was solved.

**Comment by arruix** [comment]
It is working , I can scan more than 100 qr codes, the only thing that I notice is in full mode sometimes not ready the code, I need switch to other view (50-100) and then back to full model to fixed. Really appreciate your fixed.
