### ISSUE TITLE
Result parsed code

### ISSUE THREAD

**Issue by yedeveloper** [manateeworks/phonegap-manateeworks-v3#20]
Hi @manateeworks

I'm using the plugin for scan a PDF417 code. With the parsed result, I'm doing a **substring** function. In Android i'm getting the desired result but not in IOS. The parsed string contain some blanks and tabs that Android detects but IOS does not. The parser has some influence?

 Plugin version:  3.0.43

**Comment by ghost** [comment]
Hi

Can you please send us image from the barcode that you are trying to scan so we can make some tests.

Regards,

**Comment by yedeveloper** [comment]
Hi @manateeworks 

Please, give a email to send the barcode. It contains sensitive information that can not be shown here.

Thank you

**Comment by ghost** [comment]
Hi
Can you please open ticket on `https://manateeworks.com` and our support team will help you there.
This is the link for the support `https://manateeworks.com/admin/support`

Regards,

**Comment by yedeveloper** [comment]
Hi @manateeworks 

I opened the ticket for my issue. Thank you.

Regards,
