### ISSUE TITLE
resizePartialScanner clears settings

### ISSUE THREAD

**Issue by mircerlancerous** [manateeworks/phonegap-manateeworks-v3#22]
While the method resizePartialScanner is not documented in the ReadMe, it is present in the plugin and for the most part works. The issue is that whenever the method is called, the settings loaded before startScanning are all cleared and the defaults are used. This behaviour was discovered while developing for Android.

**Comment by dimitar-gligorov** [comment]
Hi @mircerlancerous ,

The `resizePartialScanner` method is described in the ReadMe under [Configure Parameters](https://github.com/manateeworks/phonegap-manateeworks-v3#configure-parameters)
```javascript
@name "MWBresizePartialScanner"
Resizes partial scanner dimensions. If usePartialScanner is true the scanner will open in a window with these dimensions
@param[in]   left      X coordinate of left edge (percentage)
@param[in]   top       Y coordinate of top edge (percentage)
@param[in]   width     Rectangle witdh (x axis) (percentage)
@param[in]   height    Rectangle height (y axis) (percentage)
example : [{"method" : "MWBresizePartialScanner", "value" : [0,0,50,50]}] 
```
This method is also exported to `mwbScanner` and can be called as
```javascript
mwbScanner.resizePartialScanner(x,y,width,height)
```

Can you tell us which settings in particular don't work, and give us the specific use case that results in the bug you're describing above?

Regards,
Team Manatee

**Comment by ghost** [comment]
Hi @mircerlancerous ,

The `resizePartialScanner` method is described in the ReadMe under [Configure Parameters](https://github.com/manateeworks/phonegap-manateeworks-v3#configure-parameters)
```javascript
@name "MWBresizePartialScanner"
Resizes partial scanner dimensions. If usePartialScanner is true the scanner will open in a window with these dimensions
@param[in]   left      X coordinate of left edge (percentage)
@param[in]   top       Y coordinate of top edge (percentage)
@param[in]   width     Rectangle witdh (x axis) (percentage)
@param[in]   height    Rectangle height (y axis) (percentage)
example : [{"method" : "MWBresizePartialScanner", "value" : [0,0,50,50]}] 
```
This method is also exported to `mwbScanner` and can be called as
```javascript
mwbScanner.resizePartialScanner(x,y,width,height)
```

Can you tell us which settings in particular don't work, and give us the specific use case that results in the bug you're describing above?

Regards,
Team Manatee

**Comment by mircerlancerous** [comment]
Our use case is to call this method when the scanner has already been opened with `mwbScanner.startScanning(x,y,width,height)`. This bug occurs with any configuration passed via settings. In order to reduce load time, we're pre-opening the scanner and bringing it to the foreground only when needed. Ideally we would hide the camera view and leave scanning paused, then unpause and display the view when needed. This issue prevents this, however. Let me know if you need more specifics.

**Comment by ghost** [comment]
We weren't able to recreate that bug on our side.

We'll need you to send us some of your configuration files and code from your project.
Can you please [register on manateeworks.com/support](https://manateeworks.com/support/register) if you haven't got an account yet, and then once your account is activated and you're logged in, you can [submit a ticket](https://manateeworks.com/tickets/submit_ticket) and we can continue there.

Regards,
Team Manatee

**Comment by mircerlancerous** [comment]
The resize does work but then the callback set via `setCallback`, does not fire. After another resize, the blinking scan lines no longer appear. Init code is below. I do have a support account so I will duplicate this information there, and reference this issue.

`mwbScanner.setKey(Config.ManateeKeys.Android).then(function(response){
					if(!response){
						error("set key failed");
						return;
					}
					var callback = function(result){
						if(result && result.code){
							success(result.code);
						}
						else{
							error("no result");
						}
					};
					var mw_c =  mwbScanner.getConstants();
					var settings = [
						{
							method: "MWBsetActiveCodes",
							value: [
								mw_c.MWB_CODE_MASK_QR |
								mw_c.MWB_CODE_MASK_AZTEC |
								mw_c.MWB_CODE_MASK_128 |
								mw_c.MWB_CODE_MASK_25 |
								mw_c.MWB_CODE_MASK_39 |
								mw_c.MWB_CODE_MASK_93
							]
						},
						{
							method: "MWBenableZoom",
							value : [false]
						},
						{
							method: "MWBusePartialScanner",
							value: [true]
						}
					];
					if(typeof(startPaused) !== 'undefined' && startPaused){
						settings[settings.length] = {
							method: "MWBcloseScannerOnDecode",
							value: [false]
						};
						settings[settings.length] = {
							method: "MWBresumeScanning",
							value: [callback]
						};
					}
					else{
						settings[settings.length] = {
							method: "MWBcloseScannerOnDecode",
							value: [true]
						};
					}
					mwbScanner.loadSettings(settings).then(function(response){
						mwbScanner.setCallback(callback);
						//if we want to start paused
						if(typeof(isSmall) !== 'undefined' && isSmall){
							//start scanning with scanner hidden
							mwbScanner.startScanning(80,90,20,10);
							if(typeof(startPaused) !== 'undefined' && startPaused){
								//pause scanner immediately
								setTimeout(
									mwbScanner.togglePauseResume,
									2000
								);
							}
						}
						else{
							//start scanning in full screen mode
							mwbScanner.startScanning(0,25,100,50);
						}
					}).catch(function(reason){
						error(reason);
					});
				});`
