### ISSUE TITLE
fails to install on android 7.0.0

### ISSUE THREAD

**Issue by WafiqSalie** [manateeworks/phonegap-manateeworks-v3#27]
Getting the following error trying to install for android.
Failed to install 'manateeworks-barcodescanner': Error: ENOENT: no such file or directory, open '{cordovaproject}\platforms\android\AndroidManifest.xml'

**Comment by ghost** [comment]
Do you use CLI command ? If so can you text us step by step how you try to build 
These are steps how you should build:
-cordova create AppName
-cd AppName
-cordova platform add android@7.0.0
-cordova plugin add manateeworks-barcodescanner-v3

Also please text us your android studio and cordova versions.

**Comment by WafiqSalie** [comment]
argh. sorry dude. i had 
cordova plugins add manateeworks-barcodescanner
instead of 
cordova plugin add manateeworks-barcodescanner-v3.

Will the licence from version 1.5.3 work with v3 or do i need to purchase a new licence?

**Comment by ghost** [comment]
Hi
Your old license key from version 1.5.3 will not work, so you will need to purchase a new licence key.
Regards,

**Comment by WafiqSalie** [comment]
Thanks
