### ISSUE TITLE
Camera showing blank after  enable the camera permission IPAD-IOS 10.2.1 

### ISSUE THREAD

**Issue by kaviyarasu74** [manateeworks/phonegap-manateeworks-v3#6]
Steps to reproduce

>>Install the app
>>Open the barcode scanner for first time
>>it will show pop up  xxxx app  would like to access Camera
>>Click ok 
>>Blank screen appears-(no scanner its showing)

But once we close the application and reopen the app do the same steps it works

**Comment by ghost** [comment]
Hi. We are unable to reproduce the issue. Please retry the build steps and upgrade iOS to 10.3. 

Regards,

Team Manatee

**Comment by kaviyarasu74** [comment]
Updated to 10.3 still the issue persist 

am using manateworks Plugin version: 1.9.1

i dont want to update the plugin since it requires major change of my whole application functionality

is there any way to solve other than plugin update?

-kavi

**Comment by ghost** [comment]
Kavi,

We apologize, but we no longer support that version. Please upgrade at your earliest convenience. We are not seeing any issues. 

Regards,

Team Manatee
