### ISSUE TITLE
Parse Result Code

### ISSUE THREAD

**Issue by amoizesmailacn** [manateeworks/phonegap-manateeworks-v3#7]
[Hi,]

How can I parse the result code to string and remove extra characters like  asterisk(*).

This the result: 
{"location":false,"code":"*e001*1234*6789*128","imageWidth":1280,"bytes":[42,101,48,48,49,42,49,50,51,52,42,54,55,56,57,42,49,50,56],"isGS1":true,"type":"Databar 14 Stacked","imageHeight":720}

Code value: *e001*1234*6789*128
JSON Value: `*e001*1234*6789*128`

 [GS1 Code] (http://barcode.tec-it.com/en/RSS14?data=0123456789012)

**Comment by ghost** [comment]
Hello,

Have you acquired an [evaluation license key](https://manateeworks.com/lpr/new/evaluation) from the Manatee Works [Developer Network](https://manateeworks.com/developers)?

Regards,

Team Manatee

**Comment by amoizesmailacn** [comment]
@manateeworks I tried the 30-days trial.

**Comment by ghost** [comment]
Then perhaps you are not configuring your application id incorrectly. Please [contact](https://manateeworks.com/tickets/submit_ticket) our technical support team to better assist you. 

Regards,

Team Manatee
